substitutions:
  name: "smart-gate-controller"
  friendly_name: "Smart Gate"
  hidden_ssid: false
  mac_address: aabbcc # Configure MAC_Address
  devicename: gate0001

esphome:
  name: sonoff-gatecontroller
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 5min
  manual_ip:
    static_ip: # Set OWN IP ADDRESS HERE
    gateway: # SET OWN GATEWAY IP HERE
    subnet: # SET OWN SUBNET HERE
    dns1: !secret dns1
    dns2: !secret dns2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphomekey

web_server:
  local: true
  auth:
    username: admin
    password: !secret web_server_password

ota:
  password: !secret ota_password
  safe_mode: True

# If using MQTT:  
mqtt:
  broker: !secrets mqtt_broker
  username: !secrets mqtt_username
  password: !secrets mqtt_password
  discovery_unique_id_generator: mac
  log_topic: gatec/${mac_address}/logs
  #client_id: esp
  topic_prefix: gatec/${mac_address}
  birth_message:
    topic: ${devicename}/topic
    payload: online
  will_message:
    topic: ${devicename}/topic
    payload: offline


switch:
  - platform: gpio
    pin: GPIO12
    id: relay
  - platform: template
    name: "Gate Switch"
    icon: "mdi:gate"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 1s
    - switch.turn_off: relay
  - platform: gpio
    pin: GPIO5
    id: ped_sw
  - platform: template
    name: "ped"
    turn_on_action:
    - switch.turn_on: ped_sw
    - delay: 1s
    - switch.turn_off: ped_sw
  
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO14
      mode:
        input: True
    name: "Gate Open/Closed"
    id: gate_status
    device_class: door
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
      - delayed_on_off: 0.4s

      
sensor:
  - platform: wifi_signal
    name: "Wifi Signal - Gate Controller"
    update_interval: 60s
  - platform: adc
    pin: VCC
    name: "Gate VCC"
    update_interval: 60s
  # Uptime sensor
  - platform: uptime
    name: Gate uptime

text_sensor:
  - platform: version
    name: "Gate Version"
  # Expose Wifi information as a sensor
  - platform: wifi_info
    ip_address:
      name: Gate IP
    ssid:
      name: Gate SSID
    bssid:
      name: Gate BSSID



